version: '3.4'
services:
  rails: &rails
    build:
      context: .
      dockerfile: ./docker/Rails.dockerfile
    image: hitobito-dev/rails
    user: "${UID:-1000}"
    tty: true
    stdin_open: true
    depends_on:
    - db
    - mailcatcher
    - cache
    - webpack
    env_file: docker/rails.env
    environment:
      WEBPACKER_DEV_SERVER_HOST: webpack
    ports:
    - "3000:3000"
    volumes:
    - ./app/:/opt/app-root/src/
    - hitobito_bundle:/opt/bundle

  worker:
    <<: *rails
    command: [ 'rails', 'jobs:work' ]
    ports: []
    environment:
      SKIP_RAILS_MIGRATIONS: 1
    depends_on:
    - rails
    - db
    - mailcatcher
    - cache

  rails-test:
    image: hitobito-dev/rails-test
    build:
      context: .
      dockerfile: ./docker/Rails-test.dockerfile
    user: "${UID:-1000}"
    depends_on:
    - rails
    - db
    env_file: ./docker/rails.env
    environment:
      RAILS_ENV: test
      RAILS_DB_NAME: hitobito_test
      RAILS_DB_HOST: db
      RAILS_HOST_NAME: 
      DISPLAY: "${DISPLAY}"
    volumes:
    - ./app/:/opt/app-root/src/
    - hitobito_bundle:/opt/bundle
    - /tmp/.X11-unix:/tmp/.X11-unix

  # Dependencies
  mailcatcher:
    image: hitobito-dev/mailcatcher
    build:
      context: .
      dockerfile: ./docker/Mailcatcher.dockerfile
    ports:
    - "1080:1080"

  cache:
    image: memcached:1.5-alpine
    command: [ memcached, -l, '0.0.0.0', -p, '11211' ]

  sphinx:
    image: macbre/sphinxsearch:3.1.1
    command: sphinx-start
    depends_on:
    - db
    volumes:
    - ./docker/sphinx.conf:/opt/sphinx/conf/sphinx.conf:ro
    - ./docker/sphinx-start:/usr/local/bin/sphinx-start:ro
    - ./docker/sphinx-indexer:/usr/local/bin/sphinx-indexer:ro
    - sphinx_indexes:/opt/sphinx/indexes

  db:
    image: mysql:5.7
    command:
    - --sort_buffer_size=2M
    env_file: ./docker/mysql.env
    ports:
    - "33066:3306"
    volumes:
    - ./docker/mysql-setup.sql:/docker-entrypoint-initdb.d/mysql-setup.sql:ro
    - db:/var/lib/mysql

  webpack:
    build:
      context: .
      dockerfile: ./docker/Rails.dockerfile
    image: hitobito-dev/rails
    entrypoint: [ "webpack-entrypoint" ]
    env_file: docker/rails.env
    environment:
      WEBPACKER_DEV_SERVER_HOST: webpack
    user: "${UID:-1000}"
    command: /opt/app-root/src/hitobito/bin/webpack-dev-server
    ports:
    - "3035:3035"
    volumes:
    - ./app/:/opt/app-root/src/
    - hitobito_bundle:/opt/bundle
    - hitobito_yarn_cache:/opt/app-root/src/.cache/yarn

volumes:
  db:
  hitobito_bundle:
    external: true
  hitobito_yarn_cache:
    external: true
  sphinx_indexes:
